version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout
      - run:
          name: Install Nextflow
          command: curl -fsSL get.nextflow.io | bash
      - run:
          name: Run Pipeline
          command: ./nextflow run . -with-docker
