version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
      - image: pergola/pergola@sha256:f7208e45e761dc0cfd3e3915237eb1a96eead6dfa9c8f3a5b2414de9b8df3a3d
    steps:
      - checkout
      - run:
          name: Install Nextflow
          command: curl -fsSL get.nextflow.io | bash
      - run:
          name: Run Pipeline
          command: ./nextflow run . -with-docker
